### PR TITLE
Add Plugin Selection (Select All, None) button

### PR DESCRIPTION
**Pull request by Tutorgaming**
Add plugins Select All and Select None Button for handy selection :) 
image

### CODE REVIEW

**Comment by bluppfisk** [comment]
Hello @Tutorgaming , thanks for your PRs.  I'll have a look at them when I find the time this week. In the meantime, I'd like to comment on this particular PR. I'd rather see a select/clear all toggle in the top left corner of the table rather than an additional pair of buttons. Is this something you think you could do? I feel it's closer to the GTK design language

**Review by bluppfisk — CHANGES_REQUESTED** [review]
I'd prefer a more native gtk design language with a check/clear all toggle in the top left of the table

**Comment by Tutorgaming** [comment]
Actually, I've struggled for a while to implement a tick box on the top left of the TreeView T_T. 

At that time, I gave up and decided to implement that two buttons instead. Do you have any ideas or hint to look for?

**Comment by bluppfisk** [comment]
closing due to inactivity. @Tutorgaming I've changed the code base quite a bit and more changes coming. I'll still welcome a PR in the future if it complies with the GTK design language.

**Pull request closed without merging**
